rss:
  - name: Software Testing Magazine
    url: https://www.softwaretestingmagazine.com/feed/
  - name: Global App Testing Blog
    url: https://www.globalapptesting.com/blog/rss.xml
  - name: TestLodge Blog
    url: https://blog.testlodge.com/feed/
  - name: QASource Blog
    url: https://www.qasource.com/blog/rss.xml
  - name: Google Testing Blog
    url: https://testing.googleblog.com/atom.xml
  - name: Reddit GameDev QA Search
    url: "https://www.reddit.com/r/gamedev/search.rss?q=QA%20OR%20testing%20OR%20playtesting&restrict_sr=1&sort=new"
  - name: Reddit QualityAssurance Game QA Search
    url: "https://www.reddit.com/r/QualityAssurance/search.rss?q=game%20QA%20OR%20video%20game%20testing%20OR%20playtesting&restrict_sr=1&sort=new"
  - name: Reddit SoftwareTesting Game QA Search
    url: "https://www.reddit.com/r/softwaretesting/search.rss?q=game%20testing%20OR%20game%20QA%20OR%20test%20automation&restrict_sr=1&sort=new"
