rss:
  - name: Software Testing Magazine
    url: https://www.softwaretestingmagazine.com/feed/
  - name: Global App Testing Blog
    url: https://www.globalapptesting.com/blog/rss.xml
  - name: TestLodge Blog
    url: https://blog.testlodge.com/feed/
  - name: QASource Blog
    url: https://www.qasource.com/blog/rss.xml
  - name: Google Testing Blog
    url: https://testing.googleblog.com/atom.xml
  - name: Applitools Blog
    url: https://applitools.com/blog/feed/
  - name: BrowserStack Blog
    url: https://www.browserstack.com/blog/feed/
  - name: Katalon Blog
    url: https://katalon.com/resources-center/blog/rss.xml
  - name: Automation Panda
    url: https://automationpanda.com/feed/
  - name: Satisfice Blog
    url: https://www.satisfice.com/blog/feed
  - name: DevelopSense Blog
    url: https://developsense.com/blog/feed/
  - name: Martin Fowler
    url: https://martinfowler.com/feed.atom
  - name: GitHub Engineering
    url: https://github.blog/engineering/feed/
  - name: Meta Engineering
    url: https://engineering.fb.com/feed/
